# -*- coding: utf-8 -*-
"""c102 HW

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IXrmx27RYafVGvqZpMWJU1exQrTR9ZMC
"""

from random import *
user_pass=input("Enter your password, only lowercase allowed")
password = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
guess=""
while (guess !=user_pass):
  gues=""
  for letter in range(len(user_pass) - 1):
    guess_letter = password[randint(0,25)]
    guess = str(guess_letter) + str(guess)

print("Your password is ", guess)